"""
AIN State Compiler - CLI Setup & Management Tool

Commands:
  ain-brain setup          Interactive wizard: API keys, DB creds, Supabase config
  ain-brain install-ollama Download and install Ollama + pull gemma3:1b
  ain-brain cron           Register 5-minute background sync as OS cron/task
  ain-brain ingest         Run full context harvest from all configured sources
  ain-brain sync           Run a one-shot sync + compile now
  ain-brain query <text>   Ask the Company Brain a question
  ain-brain init-db        Seed the local SQLite hivemind database with mock data
  ain-brain server         Start the REST API + Dashboard server
  ain-brain version        Print version
"""

import os
import sys
import json
import argparse
import subprocess
import getpass
import platform
import urllib.request
import urllib.error


# ============================================================
# Helpers
# ============================================================

def _print(msg):
    """ASCII-safe print (avoids CP1252 crash on Windows terminals)."""
    try:
        print(msg)
    except UnicodeEncodeError:
        print(msg.encode("ascii", "replace").decode("ascii"))


def _find_project_dir():
    """Walk up from CWD to find the project root (contains mock_data/ or compiled_state/)."""
    cwd = os.getcwd()
    for candidate in [cwd] + [os.path.dirname(cwd)] * 4:
        if os.path.isdir(os.path.join(candidate, "mock_data")) or \
           os.path.isdir(os.path.join(candidate, "compiled_state")):
            return candidate
    return cwd


def _write_env(project_dir, env_vars):
    """Writes/updates .env file without overwriting existing values."""
    env_path = os.path.join(project_dir, ".env")

    existing = {}
    if os.path.exists(env_path):
        with open(env_path, "r", encoding="utf-8") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    k, _, v = line.partition("=")
                    existing[k.strip()] = v.strip()

    existing.update({k: v for k, v in env_vars.items() if v})

    with open(env_path, "w", encoding="utf-8") as f:
        f.write("# AIN State Compiler Configuration\n")
        f.write("# Generated by `ain-brain setup` -- edit manually if needed\n\n")
        for k, v in existing.items():
            f.write(f"{k}={v}\n")

    _print(f"[+] Credentials saved to {env_path}")


def _prompt(label, secret=False, default=""):
    """Prompts the user for a value, masking input if secret=True."""
    hint = f" [{default}]" if default else ""
    full_label = f"  {label}{hint}: "
    try:
        if secret:
            val = getpass.getpass(full_label)
        else:
            val = input(full_label)
        return val.strip() or default
    except (EOFError, KeyboardInterrupt):
        _print("\n[!] Setup cancelled.")
        sys.exit(0)


def _check_command_exists(cmd):
    """Returns True if cmd is on PATH."""
    try:
        subprocess.run(
            [cmd, "--version"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=5,
        )
        return True
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False


# ============================================================
# Sub-commands
# ============================================================

def cmd_version(args):
    from ain_state_compiler import __version__
    _print(f"ain-state-compiler version {__version__}")


def cmd_setup(args):
    """
    Interactive setup wizard.
    Collects and persists:
      - Slack Bot Token
      - Jira URL + API Token
      - Gmail App Password
      - Database Configuration (SQLite default vs Supabase/Postgres)
    """
    project_dir = _find_project_dir()

    _print("\n======================================================")
    _print("  AIN State Compiler -- Setup Wizard")
    _print("======================================================")
    _print("  Press Enter to skip any field and set it later.")
    _print("  PowerShell Hint: You can also configure variables directly using:")
    _print("  $env:SLACK_BOT_TOKEN=\"your-token\"")
    _print("  $env:JIRA_URL=\"https://yourorg.atlassian.net\"")
    _print("  $env:JIRA_EMAIL=\"email@domain.com\"")
    _print("  $env:JIRA_API_TOKEN=\"your-api-token\"")
    _print("  $env:GMAIL_ADDRESS=\"your-gmail@gmail.com\"")
    _print("  $env:GMAIL_APP_PASSWORD=\"your-app-password\"")
    _print("  $env:USE_SUPABASE=\"true\" (if using shared cloud hivemind)")
    _print("  $env:SUPABASE_URL=\"https://xxx.supabase.co\"")
    _print("  $env:SUPABASE_SERVICE_ROLE_KEY=\"service-role-key\"\n")

    # ---- Slack ----
    _print("[1/5] Slack Integration")
    slack_token = _prompt("Slack Bot Token (xoxb-...)", secret=True)

    # ---- Jira ----
    _print("\n[2/5] Jira Integration")
    jira_url = _prompt("Jira Base URL (e.g. https://yourorg.atlassian.net)")
    jira_email = _prompt("Jira Account Email")
    jira_token = _prompt("Jira API Token", secret=True)

    # ---- Gmail ----
    _print("\n[3/5] Gmail Integration")
    gmail_address = _prompt("Gmail Address")
    gmail_app_password = _prompt("Gmail App Password (not your login password)", secret=True)

    # ---- Database Configuration ----
    _print("\n[4/5] Database Backend Configuration")
    _print("  Local SQLite is the default backend. It is 100% offline, requires no cloud accounts, and bypasses InfoSec reviews.")
    db_choice = _prompt("Choose backend: (1) Local SQLite [Default], (2) Supabase Cloud, (3) Custom PostgreSQL", default="1")

    supabase_url = ""
    supabase_anon_key = ""
    supabase_service_key = ""
    db_host = ""
    db_port = ""
    db_name = ""
    db_user = ""
    db_password = ""

    if db_choice == "2":
        _print("\n[5/5] Supabase Configuration (Central Cloud Database)")
        _print("  Create a project at https://supabase.com, then paste credentials here.")
        supabase_url = _prompt("Supabase Project URL (e.g. https://xxxxx.supabase.co)")
        supabase_anon_key = _prompt("Supabase Anon (Public) Key", secret=True)
        supabase_service_key = _prompt("Supabase Service Role Key (admin access)", secret=True)
    elif db_choice == "3":
        _print("\n[5/5] External PostgreSQL Database Credentials")
        db_host = _prompt("DB Host")
        db_port = _prompt("DB Port", default="5432")
        db_name = _prompt("DB Name")
        db_user = _prompt("DB User")
        db_password = _prompt("DB Password", secret=True)
    else:
        _print("\n[5/5] Local SQLite selected. No database credentials required.")

    # Write to .env
    env_vars = {
        "SLACK_BOT_TOKEN": slack_token,
        "JIRA_URL": jira_url,
        "JIRA_EMAIL": jira_email,
        "JIRA_API_TOKEN": jira_token,
        "GMAIL_ADDRESS": gmail_address,
        "GMAIL_APP_PASSWORD": gmail_app_password,
        "SUPABASE_URL": supabase_url,
        "SUPABASE_ANON_KEY": supabase_anon_key,
        "SUPABASE_SERVICE_ROLE_KEY": supabase_service_key,
        "DB_HOST": db_host,
        "DB_PORT": db_port,
        "DB_NAME": db_name,
        "DB_USER": db_user,
        "DB_PASSWORD": db_password,
    }
    _write_env(project_dir, env_vars)

    _print("\n[*] Setup complete. Run `ain-brain install-ollama` to set up local LLM.")
    _print("[*] Run `ain-brain cron` to configure the 5-minute background sync.")
    _print("[*] Run `ain-brain init-db` to seed the local hivemind database.")


def cmd_install_ollama(args):
    """
    Checks if Ollama is installed. If not, downloads and installs it,
    then pulls the default model (gemma3:1b).
    """
    _print("\n[*] Checking for Ollama installation...")

    if _check_command_exists("ollama"):
        _print("[+] Ollama is already installed and on PATH.")
    else:
        system = platform.system().lower()

        if system == "windows":
            _print("[*] Downloading Ollama Windows installer...")
            installer_url = "https://ollama.com/download/OllamaSetup.exe"
            installer_path = os.path.join(os.environ.get("TEMP", os.getcwd()), "OllamaSetup.exe")
            try:
                urllib.request.urlretrieve(installer_url, installer_path)
                _print(f"[+] Installer saved to {installer_path}")
                _print("[*] Running installer silently (requires admin)...")
                subprocess.run(
                    [installer_path, "/S"],
                    check=True,
                    shell=False,
                )
                _print("[+] Ollama installed successfully.")
            except Exception as e:
                _print(f"[!] Auto-install failed: {e}")
                _print(f"    Please install Ollama manually from: {installer_url}")
                return

        elif system == "linux":
            _print("[*] Installing Ollama via curl script (Linux)...")
            try:
                subprocess.run(
                    "curl -fsSL https://ollama.com/install.sh | sh",
                    shell=True,
                    check=True,
                )
                _print("[+] Ollama installed successfully.")
            except Exception as e:
                _print(f"[!] Auto-install failed: {e}")
                _print("    Please install Ollama manually: https://ollama.com/download")
                return

        elif system == "darwin":
            _print("[*] Installing Ollama via brew (macOS)...")
            try:
                subprocess.run(["brew", "install", "ollama"], check=True)
                _print("[+] Ollama installed successfully.")
            except Exception as e:
                _print(f"[!] Auto-install failed: {e}")
                _print("    Please install Ollama manually: https://ollama.com/download")
                return
        else:
            _print(f"[!] Unsupported OS: {system}. Please install Ollama manually.")
            return

    # Pull the default model
    model = getattr(args, "model", None) or "gemma3:1b"
    _print(f"\n[*] Pulling Ollama model: {model} (this may take a few minutes)...")
    try:
        subprocess.run(["ollama", "pull", model], check=True)
        _print(f"[+] Model '{model}' ready.")
    except FileNotFoundError:
        _print("[!] Ollama not found on PATH. Please restart your terminal and try again.")
    except subprocess.CalledProcessError as e:
        _print(f"[!] Model pull failed: {e}")


def cmd_cron(args):
    """
    Registers a background 5-minute sync task.
    Windows: Windows Task Scheduler (schtasks + PowerShell)
    Linux/macOS: crontab entry
    """
    project_dir = _find_project_dir()
    python_exec = sys.executable
    system = platform.system().lower()

    _print("\n[*] Setting up 5-minute background sync task...")

    if system == "windows":
        # Build the PowerShell command to register a scheduled task
        task_name = "AINBrainSync"
        script_path = os.path.join(project_dir, "_ain_cron_sync.bat")

        bat_content = f'@echo off\n"{python_exec}" -c "from ain_state_compiler.sync import sync_from_hivemind; sync_from_hivemind(r\'{project_dir}\')" >> "{os.path.join(project_dir, "sync.log")}" 2>&1\n'
        with open(script_path, "w", encoding="utf-8") as f:
            f.write(bat_content)

        ps_script = f"""
$trigger = New-ScheduledTaskTrigger -RepetitionInterval (New-TimeSpan -Minutes 5) -Once -At (Get-Date)
$action  = New-ScheduledTaskAction -Execute '"{script_path}"'
$settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit (New-TimeSpan -Minutes 4) -StartWhenAvailable
Register-ScheduledTask -TaskName "{task_name}" -Trigger $trigger -Action $action -Settings $settings -RunLevel Highest -Force
"""
        ps_path = os.path.join(project_dir, "_register_task.ps1")
        with open(ps_path, "w", encoding="utf-8") as f:
            f.write(ps_script)

        _print(f"[*] Registering Windows Task Scheduler task '{task_name}' (needs Admin)...")
        try:
            result = subprocess.run(
                ["powershell", "-ExecutionPolicy", "Bypass", "-File", ps_path],
                capture_output=True,
                text=True,
            )
            if result.returncode == 0:
                _print(f"[+] Scheduled task '{task_name}' registered. Runs every 5 minutes.")
            else:
                _print(f"[!] Task Scheduler registration failed:\n{result.stderr.strip()}")
                _print(f"    You can register manually by running (as Admin):\n    powershell -File \"{ps_path}\"")
        except Exception as e:
            _print(f"[!] Failed to launch PowerShell: {e}")

    elif system in ("linux", "darwin"):
        sync_cmd = f'*/5 * * * * {python_exec} -c "from ain_state_compiler.sync import sync_from_hivemind; sync_from_hivemind(\'{project_dir}\')" >> {os.path.join(project_dir, "sync.log")} 2>&1'
        _print("[*] Adding crontab entry (requires user crontab access)...")
        try:
            existing = subprocess.run(
                ["crontab", "-l"],
                capture_output=True,
                text=True,
            )
            existing_crons = existing.stdout if existing.returncode == 0 else ""
            if "AINBrainSync" in existing_crons or "ain_state_compiler" in existing_crons:
                _print("[+] Cron entry already exists. Skipping.")
            else:
                new_crons = existing_crons.rstrip("\n") + f"\n# AINBrainSync\n{sync_cmd}\n"
                proc = subprocess.Popen(["crontab", "-"], stdin=subprocess.PIPE)
                proc.communicate(new_crons.encode("utf-8"))
                _print("[+] Cron job added. Sync will run every 5 minutes.")
        except Exception as e:
            _print(f"[!] crontab setup failed: {e}")
            _print(f"    Add this line to your crontab manually:\n    {sync_cmd}")
    else:
        _print(f"[!] Unsupported OS: {system}. Please configure the background task manually.")


def cmd_sync(args):
    """Run a one-shot sync + offline state compilation."""
    project_dir = _find_project_dir()
    _print("\n[*] Running one-shot hivemind sync + compile...")
    from ain_state_compiler.sync import sync_from_hivemind
    success = sync_from_hivemind(project_dir)
    if success:
        _print("[+] Sync and compilation complete.")
    else:
        _print("[!] Sync failed. Check credentials and database status.")


def cmd_query(args):
    """Ask the Company Brain a question on the CLI."""
    project_dir = _find_project_dir()
    query_text = " ".join(args.text)
    if not query_text:
        _print("[!] Please provide a query. Usage: ain-brain query <your question>")
        return

    _print(f"\n[*] Querying Company Brain: '{query_text}'")
    sys.path.insert(0, project_dir)

    # Try importing from installed package first, fall back to local file
    try:
        from ain_state_compiler.query import query_brain
    except ImportError:
        try:
            # Load old-style query_brain.py from project root
            import importlib.util
            spec = importlib.util.spec_from_file_location(
                "query_brain", os.path.join(project_dir, "query_brain.py")
            )
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            query_brain = mod.query_brain
        except Exception as e:
            _print(f"[!] Could not load query module: {e}")
            return

    ans, node, is_llm = query_brain(query_text)
    _print("\n======================================================")
    _print("  AIN COMPANY BRAIN - ANSWER")
    _print("======================================================")
    _print(f"  Context Node  : {node}")
    _print(f"  LLM Inference : {is_llm}")
    _print("------------------------------------------------------")
    _print(ans)
    _print("======================================================\n")


def cmd_init_db(args):
    """Seed the local SQLite hivemind database with mock data."""
    project_dir = _find_project_dir()
    _print("\n[*] Initializing local Hivemind database with seed data...")
    sys.path.insert(0, project_dir)
    try:
        import importlib.util
        init_path = os.path.join(project_dir, "init_hivemind_db.py")
        if os.path.exists(init_path):
            spec = importlib.util.spec_from_file_location("init_hivemind_db", init_path)
            mod = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(mod)
            mod.init_db()
        else:
            _print("[!] init_hivemind_db.py not found. Database not seeded.")
    except Exception as e:
        _print(f"[!] DB init failed: {e}")


def cmd_ingest(args):
    """
    Run full context harvest from all configured sources (Slack, Jira, Gmail).
    Uses credentials from .env file.
    Indexes all results into SQLite FTS5 (context_index.db).
    Prints readiness banner when done.
    """
    project_dir = _find_project_dir()
    _print("\n[*] Starting full context harvest...")
    try:
        from ain_state_compiler.ingest.orchestrator import orchestrate_ingest
        manifest = orchestrate_ingest(project_dir)
        _print(f"[+] Harvest complete. {manifest['grand_total_in_index']:,} records indexed.")
        _print(f"[+] Manifest saved: {os.path.join(project_dir, 'ingest_manifest.json')}")
    except Exception as e:
        _print(f"[!] Ingest failed: {e}")
        import traceback
        traceback.print_exc()


def cmd_server(args):
    """Start the REST API + Dashboard server."""
    project_dir = _find_project_dir()
    _print("\n[*] Starting AIN State Compiler server...")
    server_path = os.path.join(project_dir, "main.py")
    if not os.path.exists(server_path):
        _print(f"[!] main.py not found at {server_path}")
        return
    try:
        subprocess.run([sys.executable, server_path])
    except KeyboardInterrupt:
        _print("\n[*] Server stopped.")


# ============================================================
# CLI Entry Point
# ============================================================

def main():
    parser = argparse.ArgumentParser(
        prog="ain-brain",
        description="AIN State Compiler -- Company Brain Management CLI",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Commands:
  setup          Interactive wizard: API keys, DB creds, Supabase config
  install-ollama Download and install Ollama + pull gemma3:1b
  cron           Register 5-minute background sync as OS cron/task
  ingest         Run full context harvest from all sources (Slack+Jira+Gmail)
  sync           Run one-shot sync + compile now
  query <text>   Ask the Company Brain a question
  init-db        Seed the local SQLite hivemind database
  server         Start the REST API + Dashboard server
  version        Print version
""",
    )

    sub = parser.add_subparsers(dest="command")

    sub.add_parser("setup", help="Interactive API key and database setup wizard")

    p_ollama = sub.add_parser("install-ollama", help="Install Ollama + pull LLM model")
    p_ollama.add_argument("--model", default="gemma3:1b", help="Model to pull (default: gemma3:1b)")

    sub.add_parser("cron", help="Register 5-min background sync as OS scheduled task")
    sub.add_parser("ingest", help="Run full context harvest: Slack + Jira + Gmail -> FTS5 index")
    sub.add_parser("sync", help="Run a one-shot sync + compile now")

    p_query = sub.add_parser("query", help="Ask the Company Brain a question")
    p_query.add_argument("text", nargs="+", help="Query text")

    sub.add_parser("init-db", help="Seed the local SQLite hivemind database")
    sub.add_parser("server", help="Start the REST API + Dashboard server")
    sub.add_parser("version", help="Print version")

    args = parser.parse_args()

    dispatch = {
        "setup": cmd_setup,
        "install-ollama": cmd_install_ollama,
        "cron": cmd_cron,
        "ingest": cmd_ingest,
        "sync": cmd_sync,
        "query": cmd_query,
        "init-db": cmd_init_db,
        "server": cmd_server,
        "version": cmd_version,
    }

    handler = dispatch.get(args.command)
    if handler:
        handler(args)
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
